name: folly_fields_example
description: A new Flutter project.

publish_to: 'none'

version: 0.0.20+20

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://github.com/edufolly/folly_fields
  folly_fields:
    path: ../

  # https://pub.dev/packages/http
  http: 0.12.2
  # https://pub.dev/packages/url_launcher
  url_launcher: ^5.7.10
  # https://pub.dev/packages/google_fonts
  google_fonts: ^1.1.2
  # https://pub.dev/packages/flutter_highlight
  flutter_highlight: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/pedantic
  pedantic: ^1.9.0

flutter:
  uses-material-design: true
