name: folly_fields_example
description: A new Flutter project.

publish_to: 'none'

version: 0.0.7+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://github.com/edufolly/folly_fields
  folly_fields:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/pedantic
  pedantic: ^1.9.0

flutter:
  uses-material-design: true
