name: folly_fields_example
description: A new Flutter project.

publish_to: 'none'

version: 1.2.2+187

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # https://pub.dev/packages/connectivity_plus
  connectivity_plus: 4.0.1

  flutter:
    sdk: flutter

  # https://pub.dev/packages/flutter_highlight
  flutter_highlight: 0.7.0

  # https://flutter.dev/
  flutter_localizations:
    sdk: flutter

  # https://github.com/edufolly/folly_fields
  folly_fields:
    path: ../

  # https://pub.dev/packages/font_awesome_flutter
  font_awesome_flutter: ^10.5.0

  # https://pub.dev/packages/google_fonts
  google_fonts: 5.1.0

  # https://pub.dev/packages/http
  http: ^1.1.0

  # https://pub.dev/packages/url_launcher
  url_launcher: 6.1.12

dev_dependencies:
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
