name: Site Deploy
on:
  push:
    branches: [ dev ]

jobs:

  #############
  # Build Web #
  #############
  test:
    name: Flutter Tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Get pubspec version
        run: |
          export VERSION=$(grep 'version:' pubspec.yaml | cut -c 10- | cut -f 1 -d '+')D
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Flutter environment
        uses: subosito/flutter-action@v2

      - name: Flutter config
        run: flutter config --enable-web --no-analytics

      - name: Flutter pub get
        run: flutter pub get

      - name: Flutter test
        run: flutter test

      - name: Creating a GitHub Tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          custom_tag: ${{ env.VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true


  #############
  # Build Web #
  #############
  build-web:
    needs: [ test ]
    name: Flutter Web Build
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Test env
        run: |
          echo v${{ env.VERSION }}

      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Get pubspec version
        run: |
          export VERSION=$(grep 'version:' pubspec.yaml | cut -c 10- | cut -f 1 -d '+')D
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Flutter environment
        uses: subosito/flutter-action@v2

      - name: Flutter config
        run: flutter config --enable-web --no-analytics

      - name: Flutter pub get
        run: flutter pub get

      - name: Flutter build web
        run: |
          cd example
          flutter build web --base-href /folly_fields/

#      - name: Publishing gh-pages
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          publish_dir: ./example/build/web
#          github_token: ${{ secrets.GITHUB_TOKEN }}


  ###############
  # Build Linux #
  ###############
  build-linux:
    needs: [ test ]
    name: Flutter Linux Native Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
             sudo apt-get update -y
             sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev

      - name: Get pubspec version
        run: |
          export VERSION=$(grep 'version:' pubspec.yaml | cut -c 10- | cut -f 1 -d '+')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Flutter environment
        uses: subosito/flutter-action@v2

      - name: Flutter config
        run: flutter config --enable-linux-desktop --no-analytics

      - name: Flutter pub get
        run: flutter pub get

      - name: Flutter build linux
        run: |
          cd example
          flutter build linux

      - name: Check the current dir
        run: pwd

      - name: Build App Image
        run: |
          cd example/linux
          mkdir -p AppDir/usr/bin
          cp -r ../build/linux/x64/release/bundle/. AppDir/usr/bin/
          ln -sr AppDir/usr/bin/example AppDir/folly-fields-example
          wget -q -O appimagetool https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod a+x appimagetool
          ./appimagetool AppDir folly-fields-example.AppImage

      - name: Create a GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          artifacts: "folly-fields-example.AppImage"
