name: Dev CI
on:
  push:
    branches: [ dev ]

jobs:
  ########
  # Boot #
  ########
  boot:
    name: Boot
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version-step.outputs.version }}
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Get Pubspec Version
        id: version-step
        run: |
          export VERSION=$(grep 'version:' pubspec.yaml | cut -c 10- | cut -f 1 -d '+')
          echo "::set-output name=version::$VERSION"

  #################
  # Windows Build #
  #################
  windows-build:
    name: Windows Build
    runs-on: windows-latest
    needs: [ boot ]
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Flutter Environment
        uses: subosito/flutter-action@v2

      - name: Flutter Config
        run: flutter config --enable-windows-desktop --no-analytics

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Flutter Build Windows Native
        working-directory: example
        run: flutter build windows

      - name: Compress Flutter Build
        working-directory: example
        run: Compress-Archive build/windows/runner/Release folly-fields-example-windows.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: folly-fields-example-windows
          path: example/folly-fields-example-windows.zip
          retention-days: 1
