name: Main CI
on:
  push:
    branches: [ main ]

jobs:
  ###########
  # Version #
  ###########
  boot:
    name: Get Version
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Get Pubspec Version
        id: version-step
        run: |
          export VERSION=$(grep 'version:' pubspec.yaml | cut -c 10- | cut -f 1 -d '+')
          echo "::set-output name=version::$VERSION"
    outputs:
      version: ${{ steps.version-step.outputs.version }}


  ###################
  # Tests & Release #
  ###################
  test:
    name: Tests & Release
    runs-on: ubuntu-latest
    needs: [ boot ]
    permissions:
      contents: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Flutter Environment
        uses: subosito/flutter-action@v2

      - name: Flutter Config
        run: flutter config --no-analytics

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Flutter Test
        run: flutter test

      - name: Creating a GitHub Tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          custom_tag: ${{ needs.boot.outputs.version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ needs.boot.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true


  #############
  # Build Web #
  #############
  build-web:
    needs: [ test ]
    name: GitHub Pages Build
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Flutter Environment
        uses: subosito/flutter-action@v2

      - name: Flutter Config
        run: flutter config --enable-web --no-analytics

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Flutter Build Web
        working-directory: example
        run: flutter build web --base-href /folly_fields/

      - name: Publishing to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./example/build/web
          github_token: ${{ secrets.GITHUB_TOKEN }}


  ###############
  # Build Linux #
  ###############
  build-linux:
    needs: [ test ]
    name: Linux Native Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev

      - name: Flutter Environment
        uses: subosito/flutter-action@v2

      - name: Flutter Config
        run: flutter config --enable-linux-desktop --no-analytics

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Flutter Build Linux Native
        working-directory: example
        run: flutter build linux

      - name: Compress Flutter Build
        working-directory: example
        run: tar -cvzf folly-fields-example-linux.tar.gz build/linux/x64/release/bundle

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: folly-fields-example-linux
          path: example/folly-fields-example-linux.tar.gz
          retention-days: 7


  ########################
  # Dist Linux App Image #
  ########################
  dist-linux-app-image:
    needs: [ boot, build-linux ]
    name: Dist Linux App Image
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: folly-fields-example-linux
          path: example

      - name: List Root
        run: ls -la

      - name: List Example
        working-directory: example
        run: ls -la

      - name: Decompress Flutter Build
        working-directory: example
        run: tar -xvzf folly-fields-example-linux.tar.gz

      - name: List Example
        working-directory: example
        run: ls -la

      - name: Build App Image
        working-directory: example/linux
        run: |
          mkdir -p AppDir/usr/bin
          cp -r ../build/linux/x64/release/bundle/. AppDir/usr/bin/
          ln -sr AppDir/usr/bin/example AppDir/folly-fields-example
          wget -q -O appimagetool https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod a+x appimagetool
          ./appimagetool AppDir ../../folly-fields-example.AppImage

      - name: Adding AppImage to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ needs.boot.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          artifacts: "*.AppImage"
