name: Main CI
on:
  push:
    branches: [ test_ci ]

jobs:
  ###########
  # Version #
  ###########
  version-job:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Get Pubspec Version
        id: version-step
        run: |
          export VERSION=$(grep 'version:' pubspec.yaml | cut -c 10- | cut -f 1 -d '+')
          echo "::set-output name=version::$VERSION"
    outputs:
      version-out: ${{ steps.version-step.outputs.version }}

  ###################
  # Tests & Release #
  ###################
  test:
    name: Tests & Release
    runs-on: ubuntu-latest
    needs: [ version-job ]
    steps:
      - name: Test
        run: echo ${{ needs.version-job.outputs.version-out }}
